export const PathRoute = {
  login: "login",
  register: "/register",
  logout: "logout",
  user: "user",
  account: "account",
  profile: "profile",
  dashboard: "dashboard",
  university: "universities",
  event: "event",
  histories: "histories",
  setting: "setting",
  authorization: "/authorization",
  authorization_user_group: `/user-group`,
  authorization_role: "/role",
  authorization_permission: "/permission",
} as const;
